### ISSUE TITLE
MultipleSelect 컴포넌트가 버튼계열 컴포넌트에 미치는 오류

### ISSUE THREAD

**Issue by Han-D-Peter** [DDD-Community/DDD7-SSR-Frontend#22]
![Screen Shot 2022-06-09 at 4 36 31 PM](https://user-images.githubusercontent.com/57760806/172791450-5086f81a-03bc-414d-91e7-6b417d5f0a83.png)
- 멀티플셀렉트 컴포넌트가 다른 버튼들과 시블링으로 사용되었을때
<br/>

![오류확인](https://user-images.githubusercontent.com/57760806/172792666-fc54a028-a661-4179-9df0-ddd895aedae4.gif)
- 다른 버튼들이 동작하지 않는 문제가 발생합니다.
<br/>

|  수정전  |  수정후  |
| :------------: | :----------: |
| ![수정전](https://user-images.githubusercontent.com/57760806/172792847-e3e01f2a-46f8-40ce-a982-9a25ae71e383.png)| ![수정후](https://user-images.githubusercontent.com/57760806/172792896-f8756196-1e69-4266-a9af-fa9900772fba.png)|
- useOnClickOutside 훅에서 event.stopPropagation()을 삭제하면 해결되긴 하지만.. 사이드 이펙트가 무엇일지 모르겠습니다!

**Comment by geonwoomun** [comment]
event.stopPropagation 을 없애도 될거 같습니다!! 확인 감사합니다.
